# Generated by Django 6.0 on 2026-01-03 14:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_credits', models.CharField(default='0.5,1.0,1.5,2.0,2.5,3.0', help_text='Comma-separated list of available credit values (e.g., 0.5,1.0,1.5,2.0,2.5,3.0)', max_length=50)),
                ('default_case_due_days', models.PositiveIntegerField(default=7, help_text='Default number of days for case due date (1-90 days)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('rush_case_threshold_days', models.PositiveIntegerField(default=7, help_text='Threshold in days: cases with fewer days are marked as Rush', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('enable_scheduled_releases', models.BooleanField(default=True, help_text='Allow technicians to schedule delayed releases')),
                ('batch_release_time', models.TimeField(default='09:00', help_text='Time of day to process scheduled batch releases (HH:MM format, UTC)')),
                ('batch_release_enabled', models.BooleanField(default=True, help_text='Automatically process scheduled releases at batch_release_time')),
                ('benefits_software_api_url', models.CharField(blank=True, default='', help_text='Benefits-software API endpoint URL (placeholder for future integration)', max_length=500)),
                ('benefits_software_api_key', models.CharField(blank=True, default='', help_text='API key for benefits-software authentication (placeholder for future integration)', max_length=500)),
                ('benefits_software_api_enabled', models.BooleanField(default=False, help_text='Enable benefits-software API integration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
