# Generated by Django 6.0 on 2026-01-03 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_alter_case_status_alter_casedocument_file'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('case_created', 'Case Created'), ('case_updated', 'Case Updated'), ('case_submitted', 'Case Submitted'), ('case_assigned', 'Case Assigned'), ('case_reassigned', 'Case Reassigned'), ('case_status_changed', 'Status Changed'), ('document_uploaded', 'Document Uploaded'), ('document_viewed', 'Document Viewed'), ('document_downloaded', 'Document Downloaded'), ('document_deleted', 'Document Deleted'), ('note_added', 'Note Added'), ('note_deleted', 'Note Deleted'), ('review_submitted', 'Quality Review Submitted'), ('review_updated', 'Quality Review Updated'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('settings_updated', 'Settings Updated'), ('export_generated', 'Export Generated'), ('other', 'Other Activity')], help_text='Type of action performed', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action occurred')),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dictionary of field changes (before/after for updates)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which action was performed', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the action')),
                ('case', models.ForeignKey(blank=True, help_text='Related case (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cases.case')),
                ('document', models.ForeignKey(blank=True, help_text='Related document (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cases.casedocument')),
                ('related_user', models.ForeignKey(blank=True, help_text='Related user (if action is about another user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_about', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx'), models.Index(fields=['action_type', '-timestamp'], name='core_auditl_action__f8907a_idx'), models.Index(fields=['case', '-timestamp'], name='core_auditl_case_id_f73cfb_idx'), models.Index(fields=['-timestamp'], name='core_auditl_timesta_189a84_idx')],
            },
        ),
    ]
