# Generated by Django 6.0 on 2026-01-11 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_completion_delay_hours',
            field=models.PositiveIntegerField(choices=[(0, 'Immediate'), (1, '1 Hour'), (2, '2 Hours'), (3, '3 Hours'), (4, '4 Hours'), (5, '5 Hours')], default=0, help_text='Default delay (in hours, CST) before case shows as completed to member (0 = immediate)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
