# Generated by Django 6.0 on 2026-01-16 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsettings_default_completion_delay_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='batch_email_enabled',
            field=models.BooleanField(default=True, help_text='Automatically send scheduled emails via batch job'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_email_delay_hours',
            field=models.PositiveIntegerField(choices=[(0, 'Immediately'), (1, '1 Hour'), (2, '2 Hours'), (3, '3 Hours'), (4, '4 Hours'), (5, '5 Hours'), (6, '6 Hours'), (12, '12 Hours'), (24, '24 Hours')], default=0, help_text='Default delay (in hours, CST) before sending member notification email (tied to release date)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_delayed_email_notifications',
            field=models.BooleanField(default=True, help_text='Send member notification emails when case is released'),
        ),
    ]
