# Generated by Django 6.0 on 2026-01-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsettings_batch_email_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('case_created', 'Case Created'), ('case_updated', 'Case Updated'), ('case_submitted', 'Case Submitted'), ('case_assigned', 'Case Assigned'), ('case_reassigned', 'Case Reassigned'), ('case_status_changed', 'Status Changed'), ('case_details_edited', 'Case Details Edited'), ('case_resubmitted', 'Case Resubmitted'), ('case_held', 'Case Placed on Hold'), ('case_resumed', 'Case Resumed'), ('case_tier_changed', 'Case Tier Changed'), ('document_uploaded', 'Document Uploaded'), ('document_viewed', 'Document Viewed'), ('document_downloaded', 'Document Downloaded'), ('document_deleted', 'Document Deleted'), ('note_added', 'Note Added'), ('note_deleted', 'Note Deleted'), ('review_submitted', 'Quality Review Submitted'), ('review_updated', 'Quality Review Updated'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_role_changed', 'User Role Changed'), ('member_profile_updated', 'Member Profile Updated'), ('quarterly_credit_reset', 'Quarterly Credit Reset'), ('bulk_credit_reset', 'Bulk Credit Reset'), ('email_notification_sent', 'Email Notification Sent'), ('cron_job_executed', 'Cron Job Executed'), ('member_comment_added', 'Member Comment Added'), ('report_generated', 'Report Generated'), ('audit_log_accessed', 'Audit Log Accessed'), ('alert_dismissed', 'Alert Dismissed'), ('bulk_export', 'Bulk Data Export'), ('settings_updated', 'Settings Updated'), ('export_generated', 'Export Generated'), ('other', 'Other Activity')], help_text='Type of action performed', max_length=50),
        ),
    ]
