# Generated by Django 6.0 on 2026-01-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='reply_email_address',
            field=models.EmailField(default='reports@profeds.com', help_text='Reply-to email address for member notifications (admin only)', max_length=254),
        ),
    ]
