# Generated by Django 6.0 on 2026-01-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemsettings_reply_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Master toggle: Enable/disable ALL email notifications globally'),
        ),
    ]
