# Generated by Django 5.0.7 on 2026-02-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_staffnotification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffnotification',
            new_name='core_staffn_user_id_64b69e_idx',
            old_name='core_staffno_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='staffnotification',
            new_name='core_staffn_user_id_5fe8bd_idx',
            old_name='core_staffno_user_id_is_read_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('case_created', 'Case Created'), ('case_updated', 'Case Updated'), ('case_submitted', 'Case Submitted'), ('case_accepted', 'Case Accepted'), ('case_assigned', 'Case Assigned'), ('case_reassigned', 'Case Reassigned'), ('case_status_changed', 'Status Changed'), ('case_details_edited', 'Case Details Edited'), ('case_resubmitted', 'Case Resubmitted'), ('case_held', 'Case Placed on Hold'), ('case_resumed', 'Case Resumed'), ('case_tier_changed', 'Case Tier Changed'), ('document_uploaded', 'Document Uploaded'), ('member_document_uploaded', 'Member Document Uploaded'), ('document_viewed', 'Document Viewed'), ('document_downloaded', 'Document Downloaded'), ('document_deleted', 'Document Deleted'), ('note_added', 'Note Added'), ('note_deleted', 'Note Deleted'), ('review_submitted', 'Quality Review Submitted'), ('review_updated', 'Quality Review Updated'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_role_changed', 'User Role Changed'), ('member_profile_updated', 'Member Profile Updated'), ('quarterly_credit_reset', 'Quarterly Credit Reset'), ('bulk_credit_reset', 'Bulk Credit Reset'), ('email_notification_sent', 'Email Notification Sent'), ('email_notification_failed', 'Email Notification Failed'), ('cron_job_executed', 'Cron Job Executed'), ('member_comment_added', 'Member Comment Added'), ('member_updates_viewed', 'Member Updates Viewed'), ('report_generated', 'Report Generated'), ('audit_log_accessed', 'Audit Log Accessed'), ('alert_dismissed', 'Alert Dismissed'), ('bulk_export', 'Bulk Data Export'), ('settings_updated', 'Settings Updated'), ('export_generated', 'Export Generated'), ('case_ownership_taken', 'Case Ownership Taken'), ('admin_ownership', 'Admin Took Ownership'), ('case_completed', 'Case Completed'), ('case_incomplete', 'Case Marked Incomplete'), ('case_rejected', 'Case Rejected'), ('case_cancelled', 'Case Cancelled'), ('case_deleted', 'Case Deleted'), ('case_review_approved', 'Case Review Approved'), ('case_review_revisions', 'Case Review Revisions Requested'), ('case_review_corrected', 'Case Review Corrected'), ('member_change_request_created', 'Member Change Request Created'), ('member_change_request_approved', 'Member Change Request Approved'), ('member_change_request_denied', 'Member Change Request Denied'), ('other', 'Other Activity')], help_text='Type of action performed', max_length=50),
        ),
    ]
