# Generated by Django 6.0 on 2026-02-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_audit_log_action_choices_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffnotification',
            name='notification_type',
            field=models.CharField(choices=[('case_modification_error', 'Case Modification Error Flagged'), ('case_assigned', 'Case Assigned to You'), ('quality_review_feedback', 'Quality Review Feedback'), ('case_on_hold', 'Case Placed on Hold'), ('member_document_uploaded', 'Member Uploaded Document'), ('system_alert', 'System Alert')], help_text='Type of notification', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='available_credits',
            field=models.CharField(default='0.0,0.5,1.0,1.5,2.0,2.5,3.0', help_text='Comma-separated list of available credit values (e.g., 0.0,0.5,1.0,1.5,2.0,2.5,3.0)', max_length=50),
        ),
    ]
