# Generated by Django 6.0 on 2026-02-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_member_document_uploaded_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='technical_notes_template',
            field=models.TextField(blank=True, default='', help_text='HTML template pre-populated into Technical Notes when a case is accepted. Editable by admins.'),
        ),
    ]
