# Generated by Django 6.0 on 2026-02-28 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_technical_notes_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(help_text='Freeform feedback from the member')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beta_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beta Feedback',
                'verbose_name_plural': 'Beta Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
