# Generated by Django 6.0 on 2026-03-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_sso_audit_action_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='admin_sync_code',
            field=models.CharField(blank=True, default='admin', help_text='Access code for admin-level data sync access', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dev_sync_code',
            field=models.CharField(blank=True, default='Phil', help_text='Access code for developer-level data sync access (full access)', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('case_created', 'Case Created'), ('case_updated', 'Case Updated'), ('case_submitted', 'Case Submitted'), ('case_accepted', 'Case Accepted'), ('case_assigned', 'Case Assigned'), ('case_reassigned', 'Case Reassigned'), ('case_status_changed', 'Status Changed'), ('case_details_edited', 'Case Details Edited'), ('case_resubmitted', 'Case Resubmitted'), ('case_held', 'Case Placed on Hold'), ('case_resumed', 'Case Resumed'), ('case_tier_changed', 'Case Tier Changed'), ('document_uploaded', 'Document Uploaded'), ('member_document_uploaded', 'Member Document Uploaded'), ('document_viewed', 'Document Viewed'), ('document_downloaded', 'Document Downloaded'), ('document_deleted', 'Document Deleted'), ('note_added', 'Note Added'), ('note_deleted', 'Note Deleted'), ('review_submitted', 'Quality Review Submitted'), ('review_updated', 'Quality Review Updated'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_role_changed', 'User Role Changed'), ('member_profile_updated', 'Member Profile Updated'), ('quarterly_credit_reset', 'Quarterly Credit Reset'), ('bulk_credit_reset', 'Bulk Credit Reset'), ('email_notification_sent', 'Email Notification Sent'), ('email_notification_failed', 'Email Notification Failed'), ('cron_job_executed', 'Cron Job Executed'), ('member_comment_added', 'Member Comment Added'), ('member_updates_viewed', 'Member Updates Viewed'), ('report_generated', 'Report Generated'), ('audit_log_accessed', 'Audit Log Accessed'), ('alert_dismissed', 'Alert Dismissed'), ('bulk_export', 'Bulk Data Export'), ('settings_updated', 'Settings Updated'), ('export_generated', 'Export Generated'), ('case_ownership_taken', 'Case Ownership Taken'), ('admin_ownership', 'Admin Took Ownership'), ('case_completed', 'Case Completed'), ('case_incomplete', 'Case Marked Incomplete'), ('case_rejected', 'Case Rejected'), ('case_cancelled', 'Case Canceled'), ('case_deleted', 'Case Deleted'), ('case_review_approved', 'Case Review Approved'), ('case_review_revisions', 'Case Review Revisions Requested'), ('case_review_corrected', 'Case Review Corrected'), ('member_change_request_created', 'Member Change Request Created'), ('member_change_request_approved', 'Member Change Request Approved'), ('member_change_request_denied', 'Member Change Request Denied'), ('delegate_assigned', 'Delegate Assigned'), ('delegate_removed', 'Delegate Removed'), ('sso_login_failed', 'SSO Login Failed'), ('sso_auto_provision', 'SSO User Auto-Provisioned'), ('sso_sync', 'SSO Profile Synced'), ('wp_user_sync', 'WP User Sync Completed'), ('data_sync', 'Data Sync Operation'), ('other', 'Other Activity')], help_text='Type of action performed', max_length=50),
        ),
    ]
