# Generated by Django 6.0 on 2026-03-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_data_sync_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='betafeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Portal Feedback', 'verbose_name_plural': 'Portal Feedback'},
        ),
        migrations.AlterField(
            model_name='staffnotification',
            name='notification_type',
            field=models.CharField(choices=[('case_modification_error', 'Case Modification Error Flagged'), ('case_assigned', 'Case Assigned to You'), ('quality_review_feedback', 'Quality Review Feedback'), ('case_on_hold', 'Case Placed on Hold'), ('member_document_uploaded', 'Member Uploaded Document'), ('case_chat_message', 'New Case Chat Message'), ('member_change_request', 'Member Change Request'), ('system_alert', 'System Alert')], help_text='Type of notification', max_length=50),
        ),
    ]
