# Generated by Django 6.0 on 2026-04-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_chat_and_change_request_notification_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='feedback_email_1',
            field=models.EmailField(blank=True, default='', help_text='First email address to notify when portal feedback is submitted', max_length=254),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='feedback_email_1_enabled',
            field=models.BooleanField(default=False, help_text='Enable notifications to feedback email 1'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='feedback_email_2',
            field=models.EmailField(blank=True, default='', help_text='Second email address to notify when portal feedback is submitted', max_length=254),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='feedback_email_2_enabled',
            field=models.BooleanField(default=False, help_text='Enable notifications to feedback email 2'),
        ),
    ]
