# Generated by Django 6.0 on 2026-06-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_error_flag_disputed_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the holiday', unique=True)),
                ('name', models.CharField(help_text='Name of the holiday', max_length=100)),
                ('is_custom', models.BooleanField(default=False, help_text='False = synced from US federal calendar; True = added by admin')),
                ('active', models.BooleanField(default=True, help_text='Inactive holidays are ignored when calculating due dates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
            },
        ),
    ]
