# Generated by Django 6.0 on 2025-12-20 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_case_id', models.CharField(help_text='Generated by benefits-software API', max_length=50, unique=True)),
                ('workshop_code', models.CharField(max_length=50)),
                ('employee_first_name', models.CharField(max_length=100)),
                ('employee_last_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('num_reports_requested', models.PositiveIntegerField(default=1)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('hold', 'Hold'), ('pending_review', 'Pending Review'), ('completed', 'Completed')], default='submitted', max_length=20)),
                ('tier', models.CharField(blank=True, choices=[('tier_1', 'Tier 1'), ('tier_2', 'Tier 2'), ('tier_3', 'Tier 3')], help_text='Tech/Admin only - not visible to members', max_length=10)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_accepted', models.DateTimeField(blank=True, null=True)),
                ('date_due', models.DateField(blank=True, help_text='Tech/Admin only - not visible to members', null=True)),
                ('date_scheduled', models.DateField(blank=True, help_text='Tech/Admin only - not visible to members', null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('report_notes', models.JSONField(default=list, help_text='Array of report statuses for multi-report cases')),
                ('notes', models.TextField(blank=True, help_text='Internal notes not visible to member')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(limit_choices_to={'role': 'member'}, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_cases', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'technician', 'user_level__in': ['level_2', 'level_3']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('fact_finder', 'Federal Fact Finder Form'), ('supporting', 'Supporting Document'), ('report', 'Generated Report'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='case_documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Document',
                'verbose_name_plural': 'Case Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal notes not visible to members')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_notes', to='cases.case')),
            ],
            options={
                'verbose_name': 'Case Note',
                'verbose_name_plural': 'Case Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='case_reports/%Y/%m/%d/')),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='cases.case')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Report',
                'verbose_name_plural': 'Case Reports',
                'ordering': ['case', 'report_number'],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['external_case_id'], name='cases_case_externa_e70d20_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', '-date_submitted'], name='cases_case_status_072961_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['member', '-date_submitted'], name='cases_case_member__16c36f_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['assigned_to', 'status'], name='cases_case_assigne_e88b3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='casereport',
            unique_together={('case', 'report_number')},
        ),
    ]
