# Generated by Django 6.0 on 2025-12-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='fact_finder_data',
            field=models.JSONField(blank=True, default=dict, help_text='Federal Fact Finder form data in structured JSON format'),
        ),
    ]
