# Generated by Django 6.0 on 2025-12-20 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_add_fact_finder_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='api_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', help_text='Status of API sync to benefits-software', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='api_synced_at',
            field=models.DateTimeField(blank=True, help_text='When the case was successfully synced to benefits-software', null=True),
        ),
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='API endpoint URL called', max_length=500)),
                ('request_payload', models.JSONField(help_text='Request data sent to API')),
                ('response_status_code', models.IntegerField(blank=True, help_text='HTTP status code from API response', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Response data from API', null=True)),
                ('success', models.BooleanField(default=False, help_text='Whether the API call was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if call failed')),
                ('attempt_number', models.IntegerField(default=1, help_text='Retry attempt number (1 = first attempt)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the API call was initiated')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the API call completed (success or failure)', null=True)),
                ('case', models.ForeignKey(help_text='Case associated with this API call', on_delete=django.db.models.deletion.CASCADE, related_name='api_call_logs', to='cases.case')),
            ],
            options={
                'verbose_name': 'API Call Log',
                'verbose_name_plural': 'API Call Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', '-created_at'], name='cases_apica_case_id_a71a5a_idx'), models.Index(fields=['success', '-created_at'], name='cases_apica_success_80ef8d_idx')],
            },
        ),
    ]
