# Generated by Django 6.0 on 2025-12-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_add_api_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='fact_finder_pdf_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the PDF was successfully generated', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='fact_finder_pdf_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of Federal Fact Finder PDF generation', max_length=20),
        ),
    ]
