# Generated by Django 6.0 on 2025-12-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_federalfactfinder'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalfactfinder',
            name='spouse_fed_emp',
            field=models.BooleanField(blank=True, null=True, verbose_name='Spouse is Federal Employee'),
        ),
    ]
