# Generated by Django 6.0 on 2025-12-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_federalfactfinder_spouse_fed_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='retirement_date_preference',
            field=models.DateField(blank=True, help_text='Preferred retirement date for analysis', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='special_notes',
            field=models.TextField(blank=True, help_text='Special notes, requests, or additional information from the member'),
        ),
    ]
