# Generated by Django 6.0 on 2025-12-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_case_retirement_date_preference_case_special_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='credit_value',
            field=models.DecimalField(blank=True, choices=[(0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0')], decimal_places=1, help_text='Credit value assigned by technician based on complexity and number of reports. Members can view but not change.', max_digits=3, null=True),
        ),
    ]
