# Generated by Django 5.0.7 on 2026-01-01 19:37

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_case_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedocument',
            name='file',
            field=models.FileField(upload_to=cases.models.case_document_upload_path),
        ),
    ]
