# Generated by Django 6.0 on 2026-01-03 11:50

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_case_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('hold', 'Hold'), ('pending_review', 'Pending Review'), ('completed', 'Completed')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='file',
            field=models.FileField(upload_to=cases.models.case_document_upload_path),
        ),
    ]
