# Generated by Django 6.0 on 2026-01-03 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_alter_case_status_alter_casedocument_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='member',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'member'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
