# Generated by Django 5.0.7 on 2026-01-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_alter_case_status_alter_casedocument_file'),
        ('cases', '0011_alter_case_status'),
    ]

    operations = [
    ]
