# Generated by Django 5.0.7 on 2026-01-03 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0011_alter_case_member"),
        ("cases", "0011_alter_case_status"),
    ]

    operations = []
