# Generated by Django 6.0 on 2026-01-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_merge_0011_alter_case_member_0011_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='actual_release_date',
            field=models.DateTimeField(blank=True, help_text='Actual date/time when case was released to member (auto-set when status allows release)', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='scheduled_release_date',
            field=models.DateField(blank=True, help_text='Date when completed case will be released to member (null = released immediately)', null=True),
        ),
    ]
