# Generated by Django 6.0 on 2026-01-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_case_actual_release_date_case_scheduled_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_resubmitted',
            field=models.BooleanField(default=False, help_text='Indicates if this case has been resubmitted after completion'),
        ),
        migrations.AddField(
            model_name='case',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('hold', 'Hold'), ('pending_review', 'Pending Review'), ('completed', 'Completed')], help_text='Previous status before resubmission', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='resubmission_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this case has been resubmitted'),
        ),
        migrations.AddField(
            model_name='case',
            name='resubmission_date',
            field=models.DateTimeField(blank=True, help_text='When the case was resubmitted by the member', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='resubmission_notes',
            field=models.TextField(blank=True, help_text='Notes from member explaining why the case is being resubmitted'),
        ),
    ]
