# Generated by Django 6.0 on 2026-01-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_case_is_resubmitted_case_previous_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('accepted', 'Accepted'), ('hold', 'Hold'), ('pending_review', 'Pending Review'), ('completed', 'Completed')], help_text='Previous status before resubmission', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('accepted', 'Accepted'), ('hold', 'Hold'), ('pending_review', 'Pending Review'), ('completed', 'Completed')], default='submitted', max_length=20),
        ),
    ]
