# Generated by Django 6.0 on 2026-01-10 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_alter_case_previous_status_alter_case_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='credit_adjustment_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for credit adjustments from default value'),
        ),
        migrations.CreateModel(
            name='CreditAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjusted_at', models.DateTimeField(auto_now_add=True)),
                ('credit_value_before', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('credit_value_after', models.DecimalField(decimal_places=1, max_digits=3)),
                ('adjustment_reason', models.TextField(blank=True, default='')),
                ('adjustment_context', models.CharField(choices=[('submission', 'Case Submission (Default)'), ('acceptance', 'Case Acceptance (Ownership Taken)'), ('update', 'Manual Update'), ('completion', 'Case Completion')], default='update', max_length=20)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_adjustments', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_audit_logs', to='cases.case')),
            ],
            options={
                'verbose_name': 'Credit Audit Log',
                'verbose_name_plural': 'Credit Audit Logs',
                'ordering': ['-adjusted_at'],
            },
        ),
    ]
