# Generated by Django 6.0 on 2026-01-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_fix_document_type_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='actual_email_sent_date',
            field=models.DateTimeField(blank=True, help_text='Actual date/time when notification email was sent to member', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='scheduled_email_date',
            field=models.DateField(blank=True, help_text='Date when member notification email will be sent (tied to release date)', null=True),
        ),
    ]
