# Generated by Django 6.0 on 2026-01-16 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_case_actual_email_sent_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='date_rejected',
            field=models.DateTimeField(blank=True, help_text='When case was rejected and moved to needs_resubmission status', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='reassignment_history',
            field=models.JSONField(blank=True, default=list, help_text='History of case reassignments: [{from_tech, to_tech, date, reason}]'),
        ),
        migrations.AddField(
            model_name='case',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='Technician or admin who rejected this case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='rejection_notes',
            field=models.TextField(blank=True, help_text='Detailed notes about why case was rejected or what needs to be addressed'),
        ),
        migrations.AddField(
            model_name='case',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('incomplete_fff', 'Federal Fact Finder incomplete - missing required sections'), ('missing_documents', 'Missing required source documents'), ('insufficient_data', 'Insufficient data to process'), ('invalid_credit_request', 'Credit value appears incorrect'), ('tier_mismatch', 'Case tier does not match employee situation'), ('other', 'Other (see notes)')], help_text='Primary reason for rejecting case (needs_resubmission status)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('accepted', 'Accepted'), ('hold', 'Hold'), ('pending_review', 'Pending Review'), ('needs_resubmission', 'Needs Resubmission'), ('completed', 'Completed')], help_text='Previous status before resubmission', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('accepted', 'Accepted'), ('hold', 'Hold'), ('pending_review', 'Pending Review'), ('needs_resubmission', 'Needs Resubmission'), ('completed', 'Completed')], default='submitted', max_length=20),
        ),
    ]
