# Generated by Django 6.0 on 2026-01-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_case_date_rejected_case_reassignment_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='report_notes_to_member',
            field=models.TextField(blank=True, help_text='Notes from technician visible to member when case is released'),
        ),
    ]
