# Generated by Django 6.0 on 2026-01-16 17:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_case_report_notes_to_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='report_notes_to_member',
            field=tinymce.models.HTMLField(blank=True, help_text='Formatted notes from technician visible to member when case is released'),
        ),
    ]
