# Generated by Django 6.0 on 2026-01-17 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_alter_case_report_notes_to_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Notes from the reviewer on the case quality review'),
        ),
        migrations.AddField(
            model_name='case',
            name='review_status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('revisions_requested', 'Revisions Requested'), ('corrections_needed', 'Corrections Needed')], help_text='Result of quality review: approved, revisions requested, or corrections needed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the case was reviewed by Level 2/3 technician', null=True),
        ),
        migrations.CreateModel(
            name='CaseReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_action', models.CharField(choices=[('submitted_for_review', 'Submitted for Review'), ('approved', 'Approved'), ('revisions_requested', 'Revisions Requested'), ('corrections_needed', 'Corrections Needed'), ('resubmitted', 'Resubmitted After Feedback'), ('completed', 'Marked Complete')], help_text='What action was taken during this review', max_length=30)),
                ('review_notes', models.TextField(blank=True, help_text='Detailed notes from the reviewer')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, help_text='When this review action was taken')),
                ('case', models.ForeignKey(help_text='Case being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='cases.case')),
                ('original_technician', models.ForeignKey(blank=True, help_text='Level 1 technician who completed the case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_reviewed_by_others', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Level 2/3 technician performing the review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Review History',
                'verbose_name_plural': 'Case Review Histories',
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['case', '-reviewed_at'], name='cases_caser_case_id_153e5a_idx'), models.Index(fields=['reviewed_by', '-reviewed_at'], name='cases_caser_reviewe_95d869_idx'), models.Index(fields=['review_action', '-reviewed_at'], name='cases_caser_review__0bf247_idx')],
            },
        ),
    ]
