# Generated by Django 6.0 on 2026-01-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_case_review_notes_case_review_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='hold_duration_days',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Expected duration of hold in days (e.g., 0.083 for 2 hours, 1 for 1 day)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='hold_end_date',
            field=models.DateTimeField(blank=True, help_text='Expected end date of hold (null if unspecified)', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='hold_reason',
            field=models.TextField(blank=True, help_text='Reason why case is on hold'),
        ),
        migrations.AddField(
            model_name='case',
            name='hold_start_date',
            field=models.DateTimeField(blank=True, help_text='When the case was placed on hold', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='urgency',
            field=models.CharField(choices=[('normal', 'Normal'), ('rush', 'Rush')], default='normal', max_length=10),
        ),
    ]
