# Generated by Django 6.0 on 2026-01-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_case_hold_duration_days_case_hold_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='has_member_updates',
            field=models.BooleanField(default=False, help_text='Flag indicating member has provided new information/documents after submission'),
        ),
        migrations.AddField(
            model_name='case',
            name='member_last_update_date',
            field=models.DateTimeField(blank=True, help_text='When the member last updated the case (after initial submission)', null=True),
        ),
    ]
