# Generated by Django 5.0.7 on 2026-01-23 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_case_has_member_updates_case_member_last_update_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('case_put_on_hold', 'Case Put on Hold'), ('member_update_received', 'Member Update Received'), ('case_released', 'Case Released'), ('documents_needed', 'Documents Needed')], default='case_put_on_hold', help_text='Type of notification event', max_length=50)),
                ('title', models.CharField(help_text='Notification title shown to member', max_length=255)),
                ('message', models.TextField(help_text='Detailed notification message')),
                ('hold_reason', models.TextField(blank=True, help_text='If case put on hold, the reason why (captured from technician)', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether member has viewed this notification')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When notification was created')),
                ('read_at', models.DateTimeField(blank=True, help_text='When member viewed this notification', null=True)),
                ('case', models.ForeignKey(help_text='The case this notification relates to', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cases.case')),
                ('member', models.ForeignKey(help_text='Member receiving this notification', limit_choices_to={'role': 'member'}, on_delete=django.db.models.deletion.CASCADE, related_name='case_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['member', '-created_at'], name='cases_casen_member__0ed113_idx'), models.Index(fields=['member', 'is_read'], name='cases_casen_member__18ebac_idx'), models.Index(fields=['case', '-created_at'], name='cases_casen_case_id_84e60d_idx')],
            },
        ),
    ]
