# Generated by Django 5.0.7 on 2026-01-24 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_add_case_notification_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='accepted_by',
            field=models.ForeignKey(blank=True, help_text='Technician or admin who accepted/reviewed the case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
