# Generated by Django 6.0 on 2026-01-24 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_add_accepted_by_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='has_member_change_request',
            field=models.BooleanField(default=False, help_text='Flag indicating member has pending change request (extension/cancellation/info)'),
        ),
        migrations.CreateModel(
            name='CaseChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('due_date_extension', 'Request Due Date Extension'), ('cancellation', 'Request Case Cancellation'), ('additional_info', 'Request to Add Information')], help_text='Type of change being requested', max_length=25)),
                ('requested_due_date', models.DateField(blank=True, help_text='New due date if requesting extension (null for cancellations)', null=True)),
                ('cancellation_reason', models.CharField(blank=True, help_text='Reason for cancellation request (dropdown value)', max_length=100, null=True)),
                ('member_notes', models.TextField(blank=True, help_text='Additional notes/reasoning from member')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', help_text='Whether request is pending, approved, or denied', max_length=15)),
                ('technician_response_notes', models.TextField(blank=True, help_text='Technician notes when approving/denying request')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When request was created')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When technician reviewed this request', null=True)),
                ('case', models.ForeignKey(help_text='Case this request relates to', on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='cases.case')),
                ('member', models.ForeignKey(help_text='Member making the request', limit_choices_to={'role': 'member'}, on_delete=django.db.models.deletion.CASCADE, related_name='case_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Technician who reviewed/approved/denied this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Change Request',
                'verbose_name_plural': 'Case Change Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', 'status'], name='cases_casec_case_id_967b02_idx'), models.Index(fields=['member', '-created_at'], name='cases_casec_member__55840d_idx'), models.Index(fields=['status', '-created_at'], name='cases_casec_status_2060ca_idx')],
            },
        ),
    ]
