# Generated by Django 6.0 on 2026-01-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_case_has_member_change_request_casechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='has_member_new_info',
            field=models.BooleanField(default=False, help_text='Flag indicating member has uploaded new documents that technician should review'),
        ),
    ]
