# Generated by Django 6.0 on 2026-01-25 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0028_case_has_member_new_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message content - visible to both member and technician')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When message was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When message was last edited')),
                ('author', models.ForeignKey(help_text='User who wrote this message (member or benefits-technician)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_messages', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(help_text='Case this message is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cases.case')),
            ],
            options={
                'verbose_name': 'Case Message',
                'verbose_name_plural': 'Case Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['case', 'created_at'], name='cases_casem_case_id_d98842_idx'), models.Index(fields=['author', '-created_at'], name='cases_casem_author__8b55b4_idx')],
            },
        ),
    ]
