# Generated by Django 6.0 on 2026-01-25 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0029_casemessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnreadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this message became unread (when created)')),
                ('case', models.ForeignKey(help_text='For faster querying of unread messages per case', on_delete=django.db.models.deletion.CASCADE, related_name='unread_messages_for_users', to='cases.case')),
                ('message', models.ForeignKey(help_text='The message that is unread', on_delete=django.db.models.deletion.CASCADE, related_name='unread_by_users', to='cases.casemessage')),
                ('user', models.ForeignKey(help_text='User who has not yet read this message', on_delete=django.db.models.deletion.CASCADE, related_name='unread_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unread Message',
                'verbose_name_plural': 'Unread Messages',
                'indexes': [models.Index(fields=['user', 'case'], name='cases_unrea_user_id_86e914_idx'), models.Index(fields=['case', 'user'], name='cases_unrea_case_id_9961db_idx'), models.Index(fields=['user', '-created_at'], name='cases_unrea_user_id_397769_idx')],
                'unique_together': {('message', 'user')},
            },
        ),
    ]
