# Generated by Django 6.0 on 2026-01-25 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0030_unreadmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='original_case',
            field=models.ForeignKey(blank=True, help_text='If this case is a resubmission of a completed case, link to the original case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmitted_cases', to='cases.case'),
        ),
    ]
