# Generated by Django 6.0 on 2026-02-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0031_case_original_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='error_modification_count',
            field=models.PositiveIntegerField(default=0, help_text='Count of modification requests flagged as ProFeds errors - used for metrics'),
        ),
        migrations.AddField(
            model_name='case',
            name='has_profeds_error',
            field=models.BooleanField(default=False, help_text='Flag indicating member flagged this case as having ProFeds/technician error in modification request'),
        ),
    ]
