# Generated by Django 5.0.7 on 2026-02-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0032_case_error_modification_count_case_has_profeds_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status_before_hold',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('accepted', 'Accepted'), ('hold', 'Hold'), ('pending_review', 'Pending Review'), ('needs_resubmission', 'Needs Resubmission'), ('completed', 'Completed')], help_text='Status the case was in before being placed on hold (used to restore on resume)', max_length=20),
        ),
        migrations.AlterField(
            model_name='casenotification',
            name='notification_type',
            field=models.CharField(choices=[('case_put_on_hold', 'Case Put on Hold'), ('case_resumed', 'Case Resumed from Hold'), ('member_update_received', 'Member Update Received'), ('case_released', 'Case Released'), ('documents_needed', 'Documents Needed')], default='case_put_on_hold', help_text='Type of notification event', max_length=50),
        ),
    ]
