# Generated by Django 6.0 on 2026-03-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0033_hold_flow_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='credit_value',
            field=models.DecimalField(blank=True, choices=[(0.0, '0.0'), (0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0')], decimal_places=1, help_text='Credit value assigned by technician based on complexity and number of reports. Members can view but not change.', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='scheduled_email_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when member notification email will be sent (tied to release date)', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='scheduled_release_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when completed case will be released to member (null = released immediately)', null=True),
        ),
    ]
