# Generated by Django 6.0 on 2026-04-13 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0034_scheduled_release_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(help_text='What help is needed / review feedback.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('pushed_back', 'Pushed Back'), ('released', 'Released to Member'), ('escalated', 'Escalated to Another Reviewer'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('response_notes', models.TextField(blank=True, help_text='Notes from the reviewer when approving/pushing back.')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='cases.case')),
                ('parent_request', models.ForeignKey(blank=True, help_text='If escalated, points to the request that was escalated from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='cases.casereviewrequest')),
                ('requested_by', models.ForeignKey(help_text='Technician who asked for the review.', on_delete=django.db.models.deletion.CASCADE, related_name='review_requests_made', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_responses_given', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, help_text='Specific tech chosen as reviewer. NULL = all senior techs notified.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', '-created_at'], name='cases_caser_case_id_97bc78_idx'), models.Index(fields=['reviewer', 'status'], name='cases_caser_reviewe_74987c_idx'), models.Index(fields=['requested_by', '-created_at'], name='cases_caser_request_48a3f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='TechReviewSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('tier_1', 'Tier 1'), ('tier_2', 'Tier 2'), ('tier_3', 'Tier 3')], max_length=10)),
                ('requires_review', models.BooleanField(default=True, help_text='If True, cases of this tier completed by this tech must be reviewed before release.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(help_text='Admin/manager/L3 tech who last changed this setting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, related_name='review_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tech Review Setting',
                'ordering': ['technician', 'tier'],
                'unique_together': {('technician', 'tier')},
            },
        ),
    ]
