# Generated by Django 6.0 on 2026-04-18 13:36

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0035_casereviewrequest_techreviewsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemessage',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional screenshot or image attachment', null=True, upload_to=cases.models.chat_image_upload_path),
        ),
    ]
