# Generated by Django 6.0 on 2026-05-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0036_casemessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('accepted', 'Accepted'), ('hold', 'Hold'), ('pending_review', 'Pending Review'), ('needs_resubmission', 'Needs Resubmission'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], help_text='Previous status before resubmission', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('accepted', 'Accepted'), ('hold', 'Hold'), ('pending_review', 'Pending Review'), ('needs_resubmission', 'Needs Resubmission'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='status_before_hold',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('accepted', 'Accepted'), ('hold', 'Hold'), ('pending_review', 'Pending Review'), ('needs_resubmission', 'Needs Resubmission'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], help_text='Status the case was in before being placed on hold (used to restore on resume)', max_length=20),
        ),
        migrations.AlterField(
            model_name='casenotification',
            name='notification_type',
            field=models.CharField(choices=[('case_put_on_hold', 'Case Put on Hold'), ('case_resumed', 'Case Resumed from Hold'), ('member_update_received', 'Member Update Received'), ('case_released', 'Case Released'), ('documents_needed', 'Documents Needed'), ('case_declined', 'Case Declined')], default='case_put_on_hold', help_text='Type of notification event', max_length=50),
        ),
    ]
