# Generated by Django 6.0 on 2026-07-03 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0037_add_cancelled_status_and_declined_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['date_due'], name='cases_case_date_du_50b226_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['has_member_updates'], name='cases_case_has_mem_5f16c0_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['date_due', 'status'], name='cases_case_date_du_2af562_idx'),
        ),
    ]
