# Generated by Django 6.0 on 2026-07-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0038_case_cases_case_date_du_50b226_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('accepted', 'Accepted'), ('hold', 'Hold'), ('pending_review', 'Pending Review'), ('needs_resubmission', 'Needs Resubmission'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined by ProFeds')], help_text='Previous status before resubmission', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('accepted', 'Accepted'), ('hold', 'Hold'), ('pending_review', 'Pending Review'), ('needs_resubmission', 'Needs Resubmission'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined by ProFeds')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='status_before_hold',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('accepted', 'Accepted'), ('hold', 'Hold'), ('pending_review', 'Pending Review'), ('needs_resubmission', 'Needs Resubmission'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined by ProFeds')], help_text='Status the case was in before being placed on hold (used to restore on resume)', max_length=20),
        ),
    ]
