# Generated by Django 6.0 on 2026-08-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0040_alter_case_previous_status_alter_case_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
