# Generated by Django 6.0 on 2026-08-21 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0041_fix_date_submitted_remove_auto_now_add'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, help_text='Optional reminder note set by the tech when flagging', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Flag',
                'verbose_name_plural': 'Case Flags',
                'indexes': [models.Index(fields=['user', 'case'], name='cases_casef_user_id_edf433_idx'), models.Index(fields=['user', '-created_at'], name='cases_casef_user_id_324503_idx')],
                'unique_together': {('user', 'case')},
            },
        ),
    ]
