# Generated by Django 6.0 on 2026-09-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0042_add_caseflag_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereviewhistory',
            name='tech_notes',
            field=models.TextField(blank=True, help_text='Notes the original technician wrote to the reviewer when submitting the case for review'),
        ),
    ]
