# Generated by Django 6.0 on 2025-12-29 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorDelegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_submit', models.BooleanField(default=True, help_text='Delegate can submit new cases')),
                ('can_edit', models.BooleanField(default=True, help_text='Delegate can edit submitted cases')),
                ('can_view', models.BooleanField(default=True, help_text='Delegate can view cases')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(help_text='Advisor whose cases this delegate can submit', on_delete=django.db.models.deletion.CASCADE, related_name='advisor_delegates', to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(help_text='Staff member who can submit cases', on_delete=django.db.models.deletion.CASCADE, related_name='delegate_for_advisors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advisor Delegate',
                'verbose_name_plural': 'Advisor Delegates',
                'unique_together': {('delegate', 'advisor')},
            },
        ),
    ]
