# Generated by Django 6.0 on 2026-01-17 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_advisordelegate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegateAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'View Only - Read member cases and documents'), ('submit', 'Submit Cases - Can submit new cases on behalf of member'), ('edit', 'Edit Cases - Can submit and edit cases'), ('approve', 'Approve Cases - Can submit, edit, and approve cases')], default='submit', help_text='What actions the delegate can perform', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this delegate access is currently active')),
                ('grant_reason', models.CharField(blank=True, help_text='Why this delegate was granted access (optional)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delegate', models.ForeignKey(help_text='Team member receiving delegate permissions', on_delete=django.db.models.deletion.CASCADE, related_name='delegate_access_to_members', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(blank=True, help_text='Admin/Manager who granted this access (usually during member profile edit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegate_access_granted', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(help_text='Member (advisor) who is delegating authority', limit_choices_to={'role': 'member'}, on_delete=django.db.models.deletion.CASCADE, related_name='granted_delegate_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delegate Access',
                'verbose_name_plural': 'Delegate Access',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['member', 'is_active'], name='accounts_de_member__4d0854_idx'), models.Index(fields=['delegate', 'is_active'], name='accounts_de_delegat_96ab92_idx')],
                'unique_together': {('member', 'delegate')},
            },
        ),
        migrations.CreateModel(
            name='MemberCreditAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(help_text='Fiscal year for this quarter (e.g., 2026)')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], help_text='Quarter number (1-4)')),
                ('allowed_credits', models.IntegerField(default=100, help_text='Number of cases/credits allowed this quarter')),
                ('notes', models.TextField(blank=True, help_text='Admin notes about why this credit level was set')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(blank=True, help_text='Admin/Manager who set this allowance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_allowances_configured', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(help_text='Member (advisor) this credit allowance applies to', limit_choices_to={'role': 'member'}, on_delete=django.db.models.deletion.CASCADE, related_name='credit_allowances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Credit Allowance',
                'verbose_name_plural': 'Member Credit Allowances',
                'ordering': ['-fiscal_year', '-quarter'],
                'indexes': [models.Index(fields=['member', 'fiscal_year', 'quarter'], name='accounts_me_member__944879_idx')],
                'unique_together': {('member', 'fiscal_year', 'quarter')},
            },
        ),
    ]
