# Generated by Django 6.0 on 2026-01-17 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delegateaccess_membercreditallowance'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopDelegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_code', models.CharField(db_index=True, help_text='Workshop code this delegate has access to', max_length=50)),
                ('permission_level', models.CharField(choices=[('view', 'View Only - Read workshop cases and documents'), ('submit', 'Submit Cases - Can submit new cases for workshop members'), ('edit', 'Edit Cases - Can submit and edit cases'), ('approve', 'Approve Cases - Can submit, edit, and approve cases')], default='submit', help_text='What actions the delegate can perform for this workshop', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this delegate access is currently active')),
                ('grant_reason', models.CharField(blank=True, help_text='Why this delegate was assigned to this workshop (optional)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delegate', models.ForeignKey(help_text='Team member who can submit cases for this workshop', on_delete=django.db.models.deletion.CASCADE, related_name='workshop_delegates', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(blank=True, help_text='Tech/Admin who granted this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_delegates_granted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workshop Delegate',
                'verbose_name_plural': 'Workshop Delegates',
                'ordering': ['workshop_code', '-created_at'],
                'indexes': [models.Index(fields=['workshop_code', 'is_active'], name='accounts_wo_worksho_79d0b0_idx'), models.Index(fields=['delegate', 'is_active'], name='accounts_wo_delegat_fd2e96_idx')],
                'unique_together': {('workshop_code', 'delegate')},
            },
        ),
    ]
