# Generated by Django 6.0 on 2026-01-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workshopdelegate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='font_size',
            field=models.CharField(choices=[('75', '75% (Small)'), ('85', '85% (Smaller)'), ('100', '100% (Normal)'), ('115', '115% (Larger)'), ('130', '130% (Large)'), ('150', '150% (X-Large)')], default='100', help_text='Adjustable font size for accessibility', max_length=10),
        ),
    ]
