# Generated by Django 6.0 on 2026-03-01 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_font_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDelegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Benefits Technician who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegate_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(help_text='The user who can act on behalf of this member', on_delete=django.db.models.deletion.CASCADE, related_name='delegated_members', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(help_text='The member (advisor) being represented', on_delete=django.db.models.deletion.CASCADE, related_name='delegates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Delegate',
                'verbose_name_plural': 'Member Delegates',
                'ordering': ['member__last_name', 'member__first_name'],
                'indexes': [models.Index(fields=['member'], name='accounts_me_member__2aca1d_idx'), models.Index(fields=['delegate'], name='accounts_me_delegat_80df29_idx')],
                'unique_together': {('member', 'delegate')},
            },
        ),
    ]
