# Generated by Django 6.0 on 2026-03-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_memberdelegate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_id',
            field=models.IntegerField(blank=True, help_text='WP Fusion CRM contact ID — immutable SSO identifier for sync', null=True, unique=True),
        ),
    ]
