# Generated by Django 6.0 on 2026-03-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_id',
            field=models.CharField(blank=True, help_text='GHL (GoHighLevel) contact ID — immutable SSO identifier for sync', max_length=100, null=True, unique=True),
        ),
    ]
