# Generated by Django 6.0 on 2026-03-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_change_contact_id_to_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOAllowedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address allowed to SSO into this portal instance', max_length=254, unique=True)),
                ('note', models.CharField(blank=True, help_text='Optional note (e.g. "Tester - Chris", "Dev account")', max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SSO Allowed Email',
                'verbose_name_plural': 'SSO Allowed Emails',
                'ordering': ['email'],
            },
        ),
    ]
