# Generated by Django 6.0 on 2026-03-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_sso_allowed_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_test_account',
            field=models.BooleanField(default=False, help_text='Flag for permanent test accounts (Devops*). Excluded from data cleanup scripts.'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_email',
            field=models.EmailField(blank=True, default='', help_text='Override email for portal notifications. If set, HOLD/CHAT/READY emails go here instead of the SSO email.', max_length=254),
        ),
    ]
