# Generated by Django 6.0 on 2026-03-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_is_test_account_and_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pure_delegate',
            field=models.BooleanField(default=False, help_text='True if user has only the "Portal access: Delegate" tag (admin assistant, no own cases). False if also a member/advisor. Set automatically by SSO on each login.'),
        ),
    ]
