# Generated by Django 6.0 on 2026-03-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_is_pure_delegate_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdelegate',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text="Whether this delegate receives email notifications for this member's cases"),
        ),
    ]
