# Generated by Django 6.0 on 2026-03-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_email_notifications_to_memberdelegate'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdelegate',
            name='portal_notifications',
            field=models.BooleanField(default=True, help_text="Whether this delegate sees in-app notification alerts for this member's cases"),
        ),
    ]
