# Generated by Django 6.0 on 2026-04-11 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_portal_notifications_to_memberdelegate'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('case_on_hold', 'Case Placed on Hold'), ('case_resumed', 'Case Resumed from Hold'), ('case_chat', 'New Case Chat Message'), ('case_completed', 'Case Completed (Report Ready)'), ('messaging_reply', 'General Messaging Reply')], help_text='Which notification event this preference controls', max_length=30)),
                ('email_enabled', models.BooleanField(default=True, help_text='Receive email notifications for this event type')),
                ('portal_enabled', models.BooleanField(default=True, help_text='Receive in-app (portal) notifications for this event type')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The member or delegate who owns this preference', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'indexes': [models.Index(fields=['user', 'notification_type'], name='accounts_no_user_id_ddff86_idx')],
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
