# Generated by Django 6.0 on 2026-04-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_notification_preference_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Member/delegate opt-in for email notifications on their own cases.'),
        ),
        migrations.AddField(
            model_name='user',
            name='portal_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Member/delegate opt-in for in-app (portal) notifications on their own cases.'),
        ),
    ]
