# Generated by Django 6.0 on 2026-04-12 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_user_notification_toggles'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('add', 'Add Delegate'), ('remove', 'Remove Delegate')], max_length=10)),
                ('delegate_name', models.CharField(help_text='Name of the person to add/remove as delegate', max_length=200)),
                ('delegate_email', models.EmailField(blank=True, help_text='Email of the person to add as delegate (for add requests)', max_length=254)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from the member')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('existing_assignment', models.ForeignKey(blank=True, help_text='The delegate assignment to remove (for remove requests)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removal_requests', to='accounts.memberdelegate')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegate_requests_processed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='The member who submitted the request', on_delete=django.db.models.deletion.CASCADE, related_name='delegate_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delegate Request',
                'verbose_name_plural': 'Delegate Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
