# Generated by Django 6.0 on 2026-04-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_delegate_request_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegaterequest',
            name='still_with_firm',
            field=models.BooleanField(blank=True, help_text='For remove requests: True if delegate still works at the firm, False if they left', null=True),
        ),
    ]
