# Generated by Django 6.0 on 2026-04-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_still_with_firm_to_delegate_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_delegates',
            field=models.BooleanField(default=False, help_text='Can access the Delegate Management page. Granted to L3 techs at admin discretion.'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_review_settings',
            field=models.BooleanField(default=False, help_text='Can toggle review-required settings for other technicians. Granted to L3 techs at admin discretion.'),
        ),
    ]
