# Generated by Django 6.0 on 2026-06-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_ref_saved_searches'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, help_text='Last time this user made an authenticated request. Updated by LastActiveMiddleware (throttled 60s).', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_saved_searches',
            field=models.JSONField(blank=True, default=list, help_text='User-specific reference library recent searches (last 10). Shared across all cases and devices.'),
        ),
    ]
