# Generated by Django 6.0 on 2026-09-06 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_last_active_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegaterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('dismissed', 'Dismissed')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='ProvisioningAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('new_ghl_contact', 'New GHL Contact Not Provisioned'), ('missing_ghl_tag', 'Active Portal User Missing GHL Tag')], max_length=30)),
                ('contact_id', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provisioning Alert',
                'verbose_name_plural': 'Provisioning Alerts',
                'ordering': ['-first_detected_at'],
                'indexes': [models.Index(fields=['alert_type', 'resolved_at'], name='accounts_pr_alert_t_95dd4c_idx')],
            },
        ),
    ]
