"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-4-!+ec_gh4*-vap+do#iw76prls*e9j)xq%5q@n3smd3tdx1o$')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,testserver').split(',')

INTERNAL_IPS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'storages',
    'tinymce',
    # Local apps
    'core',
    'accounts',
    'cases',
    'messaging',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
                'django.template.context_processors.csrf',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database configuration - reads from environment variables
DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')

if DB_ENGINE == 'django.db.backends.mysql':
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': config('DB_NAME', default='advisor_portal'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST'),
            'PORT': config('DB_PORT', default='3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            },
        }
    }
else:
    # Default to SQLite for development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'  # Central Time Zone (CST/CDT) - ALL timestamps in system use this timezone

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploads) - Using DigitalOcean Spaces
# DigitalOcean Spaces Configuration (S3-compatible)
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default='')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='nyc3')
AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL', default='https://nyc3.digitaloceanspaces.com')
AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN', default='')
AWS_DEFAULT_ACL = config('AWS_DEFAULT_ACL', default='public-read')
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_LOCATION = 'media'  # Folder within bucket for media files

# Use Spaces if credentials are configured, otherwise use local storage
USE_SPACES = config('USE_SPACES', default=False, cast=bool)

if USE_SPACES and AWS_ACCESS_KEY_ID:
    # Use DigitalOcean Spaces for media storage
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'
    else:
        MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/{AWS_LOCATION}/'
else:
    # Fallback to local storage
    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@profeds.com')

# Site URL for building absolute links in emails
SITE_URL = config('SITE_URL', default='http://localhost:8000')

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# CSRF Settings
csrf_origins = config('CSRF_TRUSTED_ORIGINS', default='')
CSRF_TRUSTED_ORIGINS = csrf_origins.split(',') if csrf_origins else []

# Trust X-Forwarded-Proto header from nginx reverse proxy (SSL termination)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# benefits-software API Integration
BENEFITS_SOFTWARE_API_URL = config('BENEFITS_SOFTWARE_API_URL', default='https://benefits-software.example.com/api')
BENEFITS_SOFTWARE_API_KEY = config('BENEFITS_SOFTWARE_API_KEY', default='placeholder-api-key-change-in-production')
BENEFITS_SOFTWARE_API_TIMEOUT = config('BENEFITS_SOFTWARE_API_TIMEOUT', default=30, cast=int)
BENEFITS_SOFTWARE_API_MAX_RETRIES = config('BENEFITS_SOFTWARE_API_MAX_RETRIES', default=3, cast=int)

# TinyMCE Configuration for Rich Text Editing
TINYMCE_DEFAULT_CONFIG = {
    'height': 300,
    'width': '100%',
    'plugins': 'link image paste code table advlist lists autolink',
    'toolbar': 'formatselect | bold italic underline forecolor | link image | numlist bullist | code',
    'menubar': False,
    'statusbar': True,
    'paste_as_text': False,
    'convert_urls': False,
    'relative_urls': False,
    'image_caption': True,
    'image_title': True,
    'automatic_uploads': True,
    'images_upload_url': '/cases/upload-image/',
    'file_picker_types': 'image',
    'image_description': False,  # Simplify image dialog
}

# ============================================================================
# Data Sync — PROD SSH Configuration
# ============================================================================
# Used by the data sync panel to SSH into PROD and export data.
# Only needed on TEST and LOCAL. PROD doesn't use these.
PROD_SSH_USER = config('PROD_SSH_USER', default='dev')
PROD_SSH_HOST = config('PROD_SSH_HOST', default='104.248.126.74')
PROD_SSH_APP_PATH = config('PROD_SSH_APP_PATH', default='/var/www/advisor-portal')

# ============================================================================
# WP Fusion SSO — miniOrange OAuth2 Server
# ============================================================================
# Authentication is agnostic to environment. Each deployment sets its own
# WP_OAUTH_BASE_URL via .env:
#   miniOrange OAuth Server is installed on profeds.com (single instance)
#   Both test and production portals authenticate against the same WP site.
# All three OAuth endpoints are derived from that base URL.
# Client ID/Secret may differ per site — set in .env as needed.
# ============================================================================
WP_OAUTH_BASE_URL = config('WP_OAUTH_BASE_URL', default='https://profeds.com')
WP_OAUTH_CLIENT_ID = config('WP_OAUTH_CLIENT_ID', default='GIbWesmTFmehLeDLZCqRjpyfUcWDscSa')
WP_OAUTH_CLIENT_SECRET = config('WP_OAUTH_CLIENT_SECRET', default='luHBoeGKSryxWdeFBiNyPSTaXxSOboeo')
WP_OAUTH_AUTHORIZE_URL = config('WP_OAUTH_AUTHORIZE_URL', default=f'{WP_OAUTH_BASE_URL}/wp-json/moserver/authorize')
WP_OAUTH_TOKEN_URL = config('WP_OAUTH_TOKEN_URL', default=f'{WP_OAUTH_BASE_URL}/wp-json/moserver/token')
WP_OAUTH_RESOURCE_URL = config('WP_OAUTH_RESOURCE_URL', default=f'{WP_OAUTH_BASE_URL}/wp-json/moserver/resource')
WP_OAUTH_REDIRECT_URI = SITE_URL + '/accounts/sso/callback/'

# SSO Email Allowlist — restrict SSO access to specific emails (TEST server gate)
# Comma-separated list of emails. If empty/not set, ALL tagged users can SSO in.
# Set this in .env on TEST only. PROD leaves it blank = open to all tagged users.
# Example: SSO_ALLOWED_EMAILS=chris@profeds.com,devops@profeds.com
_sso_emails = config('SSO_ALLOWED_EMAILS', default='')
SSO_ALLOWED_EMAILS = [e.strip().lower() for e in _sso_emails.split(',') if e.strip()] if _sso_emails else []

# Webhook secret for real-time profile sync from WordPress (set in .env)
WP_WEBHOOK_SECRET = config('WP_WEBHOOK_SECRET', default='')

# ============================================================================
# LOGGING — ensure app-level logs reach gunicorn/journal
# ============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'accounts': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

