# Generated by Django 6.0 on 2026-03-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='broadcast_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_broadcast',
            field=models.BooleanField(default=False),
        ),
    ]
