# Generated by Django 6.0 on 2026-04-18 13:36

import messaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_broadcast_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional screenshot or image attachment', null=True, upload_to=messaging.models.message_image_upload_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
