from django.db import models
from django.conf import settings

class Case(models.Model):
    """Main case model with all 18 dashboard fields"""
    
    STATUS_CHOICES = [
        ('submitted', 'Submitted'),
        ('accepted', 'Accepted'),
        ('hold', 'Hold'),
        ('pending_review', 'Pending Review'),
        ('completed', 'Completed'),
    ]
    
    URGENCY_CHOICES = [
        ('normal', 'Normal'),
        ('urgent', 'Urgent'),
    ]
    
    TIER_CHOICES = [
        ('tier_1', 'Tier 1'),
        ('tier_2', 'Tier 2'),
        ('tier_3', 'Tier 3'),
    ]
    
    # Field 1: Case ID (auto-generated by benefits-software API)
    external_case_id = models.CharField(
        max_length=50, 
        unique=True,
        help_text='Generated by benefits-software API'
    )
    
    # Field 2: Workshop Code
    workshop_code = models.CharField(max_length=50)
    
    # Field 3: Member (Financial Advisor)
    member = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name='submitted_cases',
        limit_choices_to={'role': 'member'}
    )
    
    # Field 4: Employee First Name
    employee_first_name = models.CharField(max_length=100)
    
    # Field 5: Employee Last Name
    employee_last_name = models.CharField(max_length=100)
    
    # Field 6: Client Email (required)
    client_email = models.EmailField()
    
    # Field 7: Number of Reports Requested (per case)
    num_reports_requested = models.PositiveIntegerField(default=1)
    
    # Field 8: Urgency
    urgency = models.CharField(max_length=10, choices=URGENCY_CHOICES, default='normal')
    
    # Field 9: Status
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='submitted')
    
    # Field 10: Assigned To (Technician)
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='assigned_cases',
        limit_choices_to={'role': 'technician'}
    )
    
    # Field 11: Reviewed By (Level 2/3 Technician for Level 1 cases)
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='reviewed_cases',
        limit_choices_to={'role': 'technician', 'user_level__in': ['level_2', 'level_3']}
    )
    
    # Field 12: Tier (visible to technicians/admins only)
    tier = models.CharField(
        max_length=10, 
        choices=TIER_CHOICES, 
        blank=True,
        help_text='Tech/Admin only - not visible to members'
    )
    
    # Field 13: Date Submitted
    date_submitted = models.DateTimeField(auto_now_add=True)
    
    # Field 14: Date Accepted
    date_accepted = models.DateTimeField(null=True, blank=True)
    
    # Field 15: Date Due (visible to technicians/admins only)
    date_due = models.DateField(
        null=True, 
        blank=True,
        help_text='Tech/Admin only - not visible to members'
    )
    
    # Field 16: Date Scheduled (visible to technicians/admins only)
    date_scheduled = models.DateField(
        null=True, 
        blank=True,
        help_text='Tech/Admin only - not visible to members'
    )
    
    # Field 17: Date Completed
    date_completed = models.DateTimeField(null=True, blank=True)
    
    # Field 18: Report Notes (per-report status, stored as JSON)
    report_notes = models.JSONField(
        default=list,
        help_text='Array of report statuses for multi-report cases'
    )
    
    # Additional fields for internal tracking
    notes = models.TextField(blank=True, help_text='Internal notes not visible to member')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = 'Case'
        verbose_name_plural = 'Cases'
        ordering = ['-date_submitted']
        indexes = [
            models.Index(fields=['external_case_id']),
            models.Index(fields=['status', '-date_submitted']),
            models.Index(fields=['member', '-date_submitted']),
            models.Index(fields=['assigned_to', 'status']),
        ]
    
    def __str__(self):
        return f"Case {self.external_case_id} - {self.employee_first_name} {self.employee_last_name}"
    
    @property
    def employee_full_name(self):
        return f"{self.employee_first_name} {self.employee_last_name}"
    
    @property
    def requires_review(self):
        """Check if case requires quality review (Level 1 technician)"""
        if self.assigned_to and self.assigned_to.user_level == 'level_1':
            return True
        return False


class CaseDocument(models.Model):
    """Documents uploaded for a case (Federal Fact Finder, additional files)"""
    
    DOCUMENT_TYPE_CHOICES = [
        ('fact_finder', 'Federal Fact Finder Form'),
        ('supporting', 'Supporting Document'),
        ('report', 'Generated Report'),
        ('other', 'Other'),
    ]
    
    case = models.ForeignKey(Case, on_delete=models.CASCADE, related_name='documents')
    document_type = models.CharField(max_length=20, choices=DOCUMENT_TYPE_CHOICES)
    file = models.FileField(upload_to='case_documents/%Y/%m/%d/')
    original_filename = models.CharField(max_length=255)
    file_size = models.BigIntegerField()  # in bytes
    uploaded_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    notes = models.TextField(blank=True)
    
    class Meta:
        verbose_name = 'Case Document'
        verbose_name_plural = 'Case Documents'
        ordering = ['-uploaded_at']
    
    def __str__(self):
        return f"{self.original_filename} - Case {self.case.external_case_id}"


class CaseReport(models.Model):
    """Individual reports within a case (supports multi-report cases)"""
    
    REPORT_STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('pending_review', 'Pending Review'),
        ('completed', 'Completed'),
    ]
    
    case = models.ForeignKey(Case, on_delete=models.CASCADE, related_name='reports')
    report_number = models.PositiveIntegerField()  # 1, 2, 3, etc. within the case
    status = models.CharField(max_length=20, choices=REPORT_STATUS_CHOICES, default='pending')
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='assigned_reports'
    )
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='reviewed_reports'
    )
    report_file = models.FileField(upload_to='case_reports/%Y/%m/%d/', null=True, blank=True)
    notes = models.TextField(blank=True)
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = 'Case Report'
        verbose_name_plural = 'Case Reports'
        ordering = ['case', 'report_number']
        unique_together = ('case', 'report_number')
    
    def __str__(self):
        return f"Report {self.report_number} - Case {self.case.external_case_id}"


class CaseNote(models.Model):
    """Internal notes/comments on cases (visible only to technicians/admins)"""
    
    case = models.ForeignKey(Case, on_delete=models.CASCADE, related_name='case_notes')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    note = models.TextField()
    is_internal = models.BooleanField(
        default=True,
        help_text='Internal notes not visible to members'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = 'Case Note'
        verbose_name_plural = 'Case Notes'
        ordering = ['-created_at']
    
    def __str__(self):
        return f"Note by {self.author.username if self.author else 'Unknown'} on Case {self.case.external_case_id}"

