# Generated by Django 6.0 on 2026-05-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('subcategory', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reference Clause',
                'verbose_name_plural': 'Reference Clauses',
                'ordering': ['sort_order', 'category', 'subcategory', 'title'],
            },
        ),
    ]
