# Generated by Django 6.0 on 2026-05-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceclause',
            name='subcategory',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
