# Generated by Django 6.0 on 2026-05-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_increase_subcategory_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceclause',
            name='subcategory',
            field=models.TextField(blank=True, default=''),
        ),
    ]
